### PR TITLE
bugfix(semantic): Added diagnostic for use * in statement context.

### LINKED ISSUE #10142: bug: Glob use inside fn body silently accepted with no effect
# Bug Report

**Cairo version:**

commit `6a3c423a9`

**Current behavior:**

A glob `use foo::*;` inside a function body is silently accepted by the compiler and has no effect — no diagnostic is emitted. The import does nothing, and any subsequent reference to a name expected to be imported fails with a confusing E0006 "Function/Identifier not found" that gives no hint that the in-fn glob `use` is the culprit.

This is asymmetric with the three other `use`-shapes in the same fn-body position, which correctly fire E2075 ("Unsupported use item in statement."):

| Shape                                  | Outcome                             |
|----------------------------------------|-------------------------------------|
| `pub use core::array::ArrayTrait;`     | E1000 + E2075 (co-fire)             |
| `use core::array::ArrayTrait as AT;`   | E2075                                |
| `use core::array::{ArrayTrait, ST};`   | E2075                                |
| `use core::array::*;`                  | **SILENT, no error, no effect**     |

It is also asymmetric with the top-level glob case: `use core::array::*;` at top level under the default V2023_01 edition correctly fires E2091 ("Global `use` item is not supported in `V2023_01` edition."). The in-fn glob path routes through a different code path that misses both the E2075 and E2091 checks.

**Expected behavior:**

A glob `use foo::*;` inside a function body should be diagnosed consistently with the other use-shapes in statement position — i.e. it should fire E2075 ("Unsupported use item in statement.") — rather than being silently accepted with no effect.

**Steps to reproduce:**

1. Save the snippet below to a `.cairo` file.
2. Compile it with `cairo-compile` under the default edition (V2023_01).
3. Observe that the file compiles cleanly with no diagnostic about the in-fn glob `use`.
4. To demonstrate the no-effect aspect, replace with the companion snippet that references a name expected to be imported by the glob; observe E0006 "Function not found." on the use site, with no diagnostic pointing to the glob `use` as the cause.

**Related code:**

```cairo
fn main() {
    use core::array::*;   // SILENTLY ACCEPTED — no error, no effect
    let _ = 1_u32;
}
```

Companion no-effect demonstration:

```cairo
mod inner {
    pub fn unique_fn() -> u32 { 42 }
}
fn main() {
    use inner::*;                // silent
    let _ = unique_fn();         // E0006 'Function not found.' — proving import had no effect
}
```

**Other information:**

Source-level pointers:

- `crates/cairo-lang-semantic/src/expr/compute.rs:4848` — the use-as-statement arm emits E2075 for the non-glob use-shapes but the glob sub-shape silently returns `Ok` without emitting any diagnostic and without performing the import.
- `crates/cairo-lang-semantic/src/items/us.rs:271` — the E2091 emit site for top-level glob under `V2023_01`/`V2023_10` editions; not reached for in-fn position because the use-item path is statement-handled.

Suggested fix: in the use-as-statement arm at `compute.rs:4848`, route the glob sub-shape through the same E2075 emission path used by the other use-shapes, rather than silently returning `Ok`.

### PR DESCRIPTION
**Pull request by orizi**
## Summary

Glob (`*`) use statements in statement position (e.g., `use core::array::*;` inside a function body) now produce a proper diagnostic error (`E2075: Unsupported use item in statement`) instead of being silently accepted or causing unexpected behavior.

---

## Type of change

Please check **one**:

- [x] Bug fix (fixes incorrect behavior)
- [ ] New feature
- [ ] Performance improvement
- [ ] Documentation change with concrete technical impact
- [ ] Style, wording, formatting, or typo-only change

---

## Why is this change needed?

Glob use items inside statement position were not being caught and rejected. The existing logic only iterated over path leaves when processing `use` statements inside function bodies, but glob (`*`) paths are not leaves — they are star segments. This meant glob imports in statement position slipped through without a diagnostic, leading to incorrect behavior (regression tracked in #10142).

---

## What was the behavior or documentation before?

A glob use statement such as `use core::array::*;` inside a function body was not reported as an error, even though glob use items are unsupported in statement position.

---

## What is the behavior or documentation after?

A glob use statement inside a function body now correctly emits:

```
error[E2075]: Unsupported use item in statement.
 --> lib.cairo:2:22
    use core::array::*;
                     ^
```

---

## Related issue or discussion (if any)

Fixes #10142.

---

## Additional context

The fix introduces a call to `get_all_path_stars` alongside the existing `get_all_path_leaves` call, so that star segments in a use path are also checked and reported before leaf resolution is attempted.

### CODE REVIEW

**Comment by orizi** [comment]
* **#10148** <a href="https://app.graphite.com/github/pr/starkware-libs/cairo/10148?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/starkware-libs/cairo/10148?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by TomerStarkware — APPROVED** [review]
:lgtm:

> @TomerStarkware reviewed 2 files and all commit messages, and made 1 comment.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/10148#-:-OvjS8s895GBxbL1iFV5:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on eytan-starkware).
